//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalDBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string EmpId { get; set; }
        public string EmpName { get; set; }
        public string EmailId { get; set; }
        public decimal PhoneNo { get; set; }
        public int TotalExp { get; set; }
        public string JobId { get; set; }
    
        public virtual Job Job { get; set; }
    }
}
